name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run prettier

      - name: Run tests
        env:
          CI: true
        run: npm run test

      - name: Build project
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: fsl-test-jaggy
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: fsl-test-jaggy
          path: ./build

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1

      - name: tf init
        run: terraform init -backend-config="key=environment/prod/terraform.state" -input=false

      - name: tf workspace selection
        run: terraform workspace select prod | terraform workspace new prod

      - name: Run formatter
        run: terraform fmt

      - name: create TF vars
        run: |
          cat > terraform.tfvars << EOF
          bucket_name="prod-fsl-jaggy"
          environment="prod"
          EOF

      - name: Run tests
        run: terraform plan -out=deploy-plan.out -input=false

      - name: Run tests
        run: terraform apply -auto-approve "deploy-plan.out"