name: CI/CD DEV

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'terraform/**'

jobs:
  CI:
    uses: ./.github/workflows/ci.yaml

  CD:
    needs: CI
    if: github.base_ref == 'develop' && github.event.pull_request.merged == true
    uses: ./.github/workflows/cd.yaml
    with:
      environment: 'develop'
      bucket_name: 'web-static-develop'
      artifact_name: ${{ needs.CI.outputs.artifact_name }}
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
